// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApdd9q1NtWqDf7WWBqmAjYFWx4hNGC_rI',
    appId: '1:884458743582:web:edf21a34ddb8fd041dcb0f',
    messagingSenderId: '884458743582',
    projectId: 'opencourtfinal1',
    authDomain: 'opencourtfinal1.firebaseapp.com',
    storageBucket: 'opencourtfinal1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaM6V570jyVN7sj9yH72tyl-Jc1aS9sww',
    appId: '1:884458743582:android:f544d7d3dcf13bc31dcb0f',
    messagingSenderId: '884458743582',
    projectId: 'opencourtfinal1',
    storageBucket: 'opencourtfinal1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZGvqckeWARtW9GjnrFms0yYLeakPa1wE',
    appId: '1:884458743582:ios:4b7006de3e9976cc1dcb0f',
    messagingSenderId: '884458743582',
    projectId: 'opencourtfinal1',
    storageBucket: 'opencourtfinal1.appspot.com',
    iosBundleId: 'com.example.opencourtapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZGvqckeWARtW9GjnrFms0yYLeakPa1wE',
    appId: '1:884458743582:ios:4b7006de3e9976cc1dcb0f',
    messagingSenderId: '884458743582',
    projectId: 'opencourtfinal1',
    storageBucket: 'opencourtfinal1.appspot.com',
    iosBundleId: 'com.example.opencourtapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApdd9q1NtWqDf7WWBqmAjYFWx4hNGC_rI',
    appId: '1:884458743582:web:d5e0a7b8daed3c881dcb0f',
    messagingSenderId: '884458743582',
    projectId: 'opencourtfinal1',
    authDomain: 'opencourtfinal1.firebaseapp.com',
    storageBucket: 'opencourtfinal1.appspot.com',
  );
}
